// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhTkwjMiYpK_ACcGlP39Pxiv6gH2WwcLk',
    appId: '1:594761248144:web:9ff7df09f56dacfbbfd715',
    messagingSenderId: '594761248144',
    projectId: 'uct-app-836a5',
    authDomain: 'uct-app-836a5.firebaseapp.com',
    storageBucket: 'uct-app-836a5.appspot.com',
    measurementId: 'G-B0S2XJWMMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYQDkpH9QVW2xEe7a4iPU0BxfNTfFTdzI',
    appId: '1:594761248144:android:8524177dcfd2dacabfd715',
    messagingSenderId: '594761248144',
    projectId: 'uct-app-836a5',
    storageBucket: 'uct-app-836a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCODgiXk-Kl-oG99Arau-o7g6ggjLsoeUw',
    appId: '1:594761248144:ios:f6ac8f127b89c61ebfd715',
    messagingSenderId: '594761248144',
    projectId: 'uct-app-836a5',
    storageBucket: 'uct-app-836a5.appspot.com',
    iosBundleId: 'com.example.uctApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCODgiXk-Kl-oG99Arau-o7g6ggjLsoeUw',
    appId: '1:594761248144:ios:5c40a638c8b6d13ebfd715',
    messagingSenderId: '594761248144',
    projectId: 'uct-app-836a5',
    storageBucket: 'uct-app-836a5.appspot.com',
    iosBundleId: 'com.example.uctApp.RunnerTests',
  );
}
